version: '2'

services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend

  data-sender:
    command: npm run run

  frontend:
    command: sh -c "npm run build && http-server dist"

  api:
    command: npm run run
