version: '2'

services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend-app
    volumes:
      - "./frontend-app:/app"
    ports:
      - "8081:8081"
    depends_on:
      - api

  data-sender:
    build:
      context: ./container-data-sender
    volumes:
      - "./container-data-sender:/app"
    depends_on:
      - mosquitto
    environment:
    - MQTT_HOST=http://mosquitto:1883

  api:
    build:
      context: ./api
    volumes:
      - "./api:/app"
    ports:
      - "4000:4000"
    depends_on:
      - mosquitto
    environment:
    - MQTT_HOST=http://mosquitto:1883

  mosquitto:
    image: toke/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
