version: '3.1'

services:
  frontend:    
    build: 
      context: ./frontend-app
    volumes:
      - "./frontend:/app"
    ports:
      - "8080:8080"
    depends_on:
      - api
  
  data-sender:    
    build: 
      context: ./container-data-sender
    volumes:
      - "./data-sender:/app"    
    depends_on:
      - mosquitto

  api:    
    build: 
      context: ./api
    volumes:
      - "./api:/app"
    ports:
      - "4000:4000"
    depends_on:
      - mosquitto
      
  mosquitto:
    image: toke/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"