version: '3.1'

services:
  frontend:    
    build: 
      context: ./frontend-app
    volumes:
      - "./frontend:/app"
    ports:
      - "8080:8080"
    depends_on:
      - api

  api:    
    build: 
      context: ./api
    volumes:
      - "./api:/app"
    ports:
      - "4000:4000"
         