version: '3.1'

services:
  frontend:    
    build: 
      context: ./frontend-app
    command: npm run dev
    volumes:
      - "./frontend-app:/app"
    ports:
      - "8080:8080"
    depends_on:
      - api
  
  data-sender:    
    build: 
      context: ./container-data-sender
    command: npm run dev
    volumes:
      - "./container-data-sender:/app"    
    depends_on:
      - mosquitto
    environment:
    - MQTT_HOST=http://localhost:4000

  api:    
    build: 
      context: ./api
    command: npm run dev
    volumes:
      - "./api:/app"
    ports:
      - "4000:4000"
    depends_on:
      - mosquitto
    environment:
    - MQTT_HOST=http://localhost:4000
      
  mosquitto:
    image: toke/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"